### ISSUE TITLE
submodule can't access

### ISSUE THREAD

**Issue by zengliangjun** [ExistentialRobotics/DR_Safe_Navigation#1]
[submodule "src/erl_common"]
	path = src/erl_common
	url = https://github.com/ExistentialRobotics/erl_common.git
[submodule "src/erl_covariance"]
	path = src/erl_covariance
	url = https://github.com/ExistentialRobotics/erl_covariance.git
[submodule "src/erl_sdf_mapping"]
	path = src/erl_sdf_mapping
	url = https://github.com/ExistentialRobotics/erl_sdf_mapping.git
[submodule "src/erl_gaussian_process"]
	path = src/erl_gaussian_process
	url = https://github.com/ExistentialRobotics/erl_gaussian_process.git
[submodule "src/erl_geometry"]
	path = src/erl_geometry
	url = https://github.com/ExistentialRobotics/erl_geometry.git

these submodules can't access!!

**Comment by daizhirui** [comment]
It is caused by old commits. I already reset the commit history.

@zengliangjun Please pull and try again.
